
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.Image canvas;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.FileChooserButton loadB;
	
	private global::Gtk.Button rutaD;
	
	private global::Gtk.SpinButton aVertice;
	
	private global::Gtk.SpinButton bVertice;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Dibuja Grafos");
		this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-remove", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.canvas = new global::Gtk.Image ();
		this.canvas.Name = "canvas";
		this.vbox1.Add (this.canvas);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.canvas]));
		w1.Position = 0;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.loadB = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Seleccionar un archivo"), ((global::Gtk.FileChooserAction)(0)));
		this.loadB.Name = "loadB";
		this.hbox1.Add (this.loadB);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.loadB]));
		w2.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.rutaD = new global::Gtk.Button ();
		this.rutaD.CanFocus = true;
		this.rutaD.Name = "rutaD";
		this.rutaD.UseUnderline = true;
		this.rutaD.Label = global::Mono.Unix.Catalog.GetString ("Dibujar ruta");
		this.hbox1.Add (this.rutaD);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.rutaD]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.aVertice = new global::Gtk.SpinButton (0, 100, 1);
		this.aVertice.CanFocus = true;
		this.aVertice.Name = "aVertice";
		this.aVertice.Adjustment.PageIncrement = 10;
		this.aVertice.ClimbRate = 1;
		this.aVertice.Numeric = true;
		this.hbox1.Add (this.aVertice);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.aVertice]));
		w4.Position = 2;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.bVertice = new global::Gtk.SpinButton (0, 100, 1);
		this.bVertice.CanFocus = true;
		this.bVertice.Name = "bVertice";
		this.bVertice.Adjustment.PageIncrement = 10;
		this.bVertice.ClimbRate = 1;
		this.bVertice.Numeric = true;
		this.hbox1.Add (this.bVertice);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.bVertice]));
		w5.Position = 3;
		w5.Expand = false;
		w5.Fill = false;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.canvas.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnCanvasExposeEvent);
		this.loadB.SelectionChanged += new global::System.EventHandler (this.OnLoadBSelectionChanged);
		this.rutaD.Clicked += new global::System.EventHandler (this.OnRutaDClicked);
	}
}
